### ISSUE TITLE
Kanji to katakana conversion

### ISSUE THREAD

**Issue by gonzales-gerald** [kekyo/MeCab.DotNet#1]
Do you have an example of how can I translate kanji to katakana input?

**Comment by kekyo** [comment]
I don't have any examples related kanji to kana conversion.
I investigated bit, we can convert it with [KAKASI inverter](http://kakasi.namazu.org/index.html.en) but maybe it isn't ported to .NET libs...

**Comment by tani** [comment]
@gonzales-gerald 
Here is an example;

```fsharp
open System
open MeCab

[<EntryPoint>]
let main argv =
    let input = "行く川のながれは絶えずして、しかももとの水にあらず。"
    let tagger = MeCabTagger.Create (MeCabParam())
    input
        |> tagger.ParseToNodes
        |> Seq.filter (fun node -> node.CharType > 0u)
        |> Seq.map (fun node -> node.Feature.Split ',')
        |> Seq.iter (fun features -> printf "%s" features.[7])
    0
```
