### ISSUE TITLE
What Mecab version is used in MeCab.DotNet?

### ISSUE THREAD

**Issue by LanBN** [kekyo/MeCab.DotNet#6]
Hi,
MeCab.DotNet is a very wonderful sharing!
Which is the version of Mecab is used in MeCab.DotNet?
As written in readme, MeCab.DotNet is a ported of NMeCab, so the version of Mecab in MeCab.DotNet is 0.98, isn't it?

**Comment by kekyo** [comment]
@LanBN Thank you using MeCab.DotNet!

This version ported from original [NMeCab version 0.0.7](https://github.com/kekyo/MeCab.DotNet/commit/d266a077ccd7e0ede29252222b5c4750542a30c7) from sourceforge.jp.

Now, komutan (the original author of NMeCab) has moved it to GitHub, but I opened MeCab.DotNet first, and these codes were forked. Therefore, the interface of these codes is a little different.

Just the other day, we had a discussion about merging our projects (See #5). There is a possibility of integration in the near future, but it is still undecided.

**Comment by LanBN** [comment]
@kekyo Many thanks to your so warm answer!!!

I found that NMeCab version 0.0.7 is released on 2015-07-07,
and the lastest version of Mecab is 0.996 on 2013-02-18 (taku910.github.io/mecab/)

I thought that NMeCab was created base on MeCab (taku910.github.io), is it true?
Was NMeCab 0.0.7 created based on Mecab 0.996?

**Comment by kekyo** [comment]
@komutan Do you remember what version NMeCab 0.0.7 ports from original MeCab version?
I forgot but maybe wrote at unknown documents or articles...

---
JP:
NMeCabの0.0.7バージョン（sourceforge.jpで公開されている最後のものです）の、対応するMeCabのバージョンを覚えていますか？　私はどこかで読んだ記憶があるんですが忘れてしまいました。念のため、今sourceforge.jpに上がっているzipを全部見たのですが分からなかったので...

**Comment by komutan** [comment]
@kekyo @LanBN 
I'm sorry. I'm late to notice the mention.

`NMeCab 0.07` is based on original `MeCab 0.98`.
https://ja.osdn.net/projects/nmecab/wiki/FrontPage

The difference from `MeCab 0.99X` is ...
- The Model class and Lattice class are not exposed to the outside.
- The partial analysis function is different.

**Comment by LanBN** [comment]
@komutan This is exactly what I’ve been wanting, thank you so much!
