### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hidemat** [kekyo/MeCab.DotNet#7]
Hello. This isn't so much an issue. I just want make sure I understand the license. If I use MeCab.DotNet in a commercial project what do I have to do as a developer to respect the license? Do I have to provide the source code of my app?

> a) Accompany it with the complete corresponding machine-readable    source code, which must be distributed under the terms of Sections    1 and 2 above on a medium customarily used for software interchange; or,
> 
> b) Accompany it with a written offer, valid for at least three    years, to give any third party, for a charge no more than your    cost of physically performing source distribution, a complete    machine-readable copy of the corresponding source code, to be    distributed under the terms of Sections 1 and 2 above on a medium    customarily used for software interchange; or,
> 
> c) Accompany it with the information you received as to the offer    to distribute corresponding source code.  (This alternative is    allowed only for noncommercial distribution and only if you    received the program in object code or executable form with such    an offer, in accord with Subsection b above.)

**Comment by kekyo** [comment]
I couldn't tell you about strictly license terms and means, but can suggest it about:

* `MeCab.DotNet` and hierarchy MeCab series license under the GPL 2 and LGPL 2.1 terms.
* GPL 2 and LGPL 2.1 limitation is in following official sentence:
  * https://opensource.org/licenses/GPL-2.0
  * https://opensource.org/licenses/LGPL-2.1
* The FAQ of GPLs: https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html

-------

In my opinion:

* Short word for safer understanding about GPL 2: All source code (include your own) must makes public and/or available.
* Short word for safer understanding about LGPL 2.1: Libs (MeCab.DotNet in this case) must make public and/or available when libs are customized. You don't have to make public your own mainly code.

MeCab.DotNet is applied "Dual license" model, so you can use GPL 2 OR LGPL 2.1.

I suggest you contact legal experts if you will release your product in business usage :)

**Comment by hidemat** [comment]
どうも :)
