### ISSUE TITLE
MeCab.MeCabParam constructor is not compatible with .net6 single file application.

### ISSUE THREAD

**Issue by sudoudaisuke** [kekyo/MeCab.DotNet#8]
Hello.

.net6 single file application is not compatible with [Assembly.Location](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file/overview#api-incompatibility).

This code throws ArgumentNullException with .net6 single file application. And application does not have nomally solution.

https://github.com/kekyo/MeCab.DotNet/blob/337a364d801a36075d54baee6bc275e3f7034957/MeCab.DotNet/MeCabParam.cs#L91

This is sample program exception message.
```
System.ArgumentNullException: Value cannot be null. (Parameter 'paths')
   at System.IO.Path.Combine(String[] paths)
   at MeCab.MeCabParam.CombinePath(String[] paths)
   at MeCab.MeCabParam..ctor()
   at Program.<Main>$(String[] args) in C:\Users\sudou-daisuke\source\repos\MeCabSampleSolution\MeCabSample\Program.cs:line 5
```

[MeCabSample.zip](https://github.com/kekyo/MeCab.DotNet/files/8202391/MeCabSample.zip)

**Comment by kekyo** [comment]
Merged luojunyuan fixing and being deployed 1.0.0.
If you have any problems, reopen it.
